DonorManager2024/Models/DonorRelated/DonorFlags.cs
using DonorManager.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DonorManager2024.Models.DonorRelated
{
    public class DonorFlags
    {
        [Key]        
        public int FlagId { get; set; }

        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateAdded { get; set; } = DateTime.Now;

        //[MinLength(2)]
        public string? Comment { get; set; }

        public string FlagName { get; set; }

        public bool Visibility { get; set; }                                      

        [ForeignKey(nameof(DonorFlags))]
        public int? ClientId { get; set; }
        public Client Client { get; set; }
        
        public ICollection<Donor> Donors { get; set; }

        public ICollection<Transactions> Transactions { get; set; }

        public void DeepCopy(DonorFlags donorFlags)
        {            
            this.Comment = donorFlags.Comment;
            this.DateAdded = donorFlags.DateAdded;
            this.FlagId = donorFlags.FlagId;
            this.FlagName = donorFlags.FlagName;
            this.Visibility = donorFlags.Visibility;
        }

        //[ForeignKey(nameof(DonorFlags))]
        //public int DonorId { get; set; }
        //public Donor Donor { get; set; }
        //Donor will have a list of donor flags because donor will have a 1 to many

        //[ForeignKey(nameof(DonorFlags))]
        //public int FlagDtlId { get; set; }
        //public DonorFlagDetail DonorFlagDetail { get; set; }

        //public int FlagValue { get; set; } //set to a power of 2

        //public enum Flags : Int64
        //{
        //    None = 0,
        //    AnnualFlag = 1,
        //    MailFlag = 2,
        //    EmailFlag = 4,
        //    NoExchangeFlag = 8,
        //    DeceasedFlag = 16,
        //    NoRenewalFlag = 32,
        //    NoTMFlag = 64,
        //    WillFlag = 128,
        //    NoThankYouFlag = 256,
        //    PremiumDeclinedFlag = 512
        //}
    }
}

DonorManager2024/ViewModels/DonorFlagViewModel.cs
namespace DonorManager2024.ViewModels
{
    public class DonorFlagViewModel
    {
        public int FlagId { get; set; }

        public string Comment { get; set; }

        public string FlagName { get; set; }

        public string Visibility { get; set; }
    }
}

DonorManager2024/Controllers/DonorFlagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DonorManager2024.Data;
using DonorManager2024.Models.DonorRelated;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using DonorManager.Models;
using System.Data;
using System.Drawing;
using System.Collections.Immutable;
using System.Transactions;

namespace DonorManager2024.Controllers
{
    [Authorize(Roles = "Admin, ABData")]
    public class DonorFlagsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;

        public DonorFlagsController(ApplicationDbContext context, UserManager<ApplicationUser> manager)
        {
            _context = context;
            _manager = manager;
        }

        // GET: DonorFlags
        public async Task<IActionResult> Index(string searchString)
        {
            //var applicationDbContext = _context.DonorFlags.Include(d => d.Donor);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _manager.Users.Include(u => u.ManagedClients).Where(u => u.Id == userId).FirstOrDefault();
            var userRoles = await _manager.GetRolesAsync(user);

            List<int> ClientIds = new List<int>();
            foreach (var Client in user.ManagedClients)
            {
                ClientIds.Add(Client.ClientId);
            }
            

            //List<int> allDonorFlags = new List<int>();

            //var allDonorFlags = userRoles.Contains("Admin") || userRoles.Contains("ABData")
            //    ? await _context.DonorFlags.ToListAsync()
            //    : await _context.DonorFlags.Include(d => d.Client).Where(d => ClientIds.Contains(d.ClientId)).ToListAsync();

            var selectedFlags = userRoles.Contains("Admin") || userRoles.Contains("ABData")
                ? await _context.DonorFlags.ToListAsync()
                : await _context.DonorFlags.Include(d => d.Client).Where(d => ClientIds.Contains(d.ClientId.Value)).ToListAsync();

            // * var flagEndpoint = await _context.DonorFlags.Include(d => d.Client).Where(d => ClientIds.Contains(d.ClientId.Value)).Include(d => d.Transactions).Where(d => ).ToListAsync();

            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(searchString))
                return View(selectedFlags.ToList());

            bool success = int.TryParse(searchString, out var clientId);
            if (!success)
                searchString = "";

            if (!string.IsNullOrEmpty(searchString))
                selectedFlags = selectedFlags.Where(d => d.ClientId == clientId).ToList();

            return selectedFlags.Count != 0 ?
                View(selectedFlags) :
                NotFound("No Good. Please Try Again.");

            //return View(await applicationDbContext.ToListAsync());
            //return View();
        }

        // GET: DonorFlags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _manager.Users
                .Include(c => c.ManagedClients)
                .FirstOrDefaultAsync(u => u.Id == userId);

            if (id == null || _context.DonorFlags == null || user == null)
            {
                return NotFound();
            }

            var userRoles = await _manager.GetRolesAsync(user);

            IEnumerable<Client> selectedClients;
            
            var donorFlags = await _context.DonorFlags
                //.Include(d => d.FlagId)
                .FirstOrDefaultAsync(m => m.FlagId == id);
            if (donorFlags == null)
            {
                return NotFound();
            }

            return View(donorFlags);
        }

        // GET: DonorFlags/Create
        public async Task<IActionResult> Create()
        {
            List<int> ClientIds = new List<int>();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _manager.Users.Include(d => d.ManagedClients).Where(u => u.Id == userId).FirstOrDefaultAsync();
            var userRoles = await _manager.GetRolesAsync(user);

            //var allClientList = new List<Client>();
            var allClientList = await _context.Client.ToListAsync();

            bool isAdmin = false;
            if (userRoles.Contains("Admin") || userRoles.Contains("SuperAdmin") || userRoles.Contains("Client"))
            {
                isAdmin = true;
            }
            else
            {
                foreach (var Client in _context.Client.ToList()/*user.ManagedClients*/)
                {
                    allClientList.Add(Client);
                }
                Client allClientOption = new Client()
                {
                    ClientId = 0, ClientName = "All Clients"
                };
            }

            allClientList.Insert(0, new Client { ClientId = 0, ClientName = "All Clients" });

            ViewData["ClientName"] = new SelectList(isAdmin ? allClientList 
                : _context.Client.Where(c => ClientIds.Contains(c.ClientId)), "ClientId", "ClientName");                        

            return View();
        }

        // POST: DonorFlags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,/*[Bind("FlagId,DateAdded,Comment,DonorId")] */DonorFlags donorFlags)
        {
            try
            {
                var donorFlagDb = _context.DonorFlags.Include(d => d.Client).Where(d => d.FlagId == id).FirstOrDefault();
                if (donorFlags.ClientId.Value == 0)
                    donorFlags.ClientId = null;
                _context.DonorFlags.Add(donorFlags);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "404 ERROR! " + "Your data failed to save. " + "Please contact your system administrator.");
            }
            return View(donorFlags);
            
        }

        // GET: DonorFlags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DonorFlags == null)
            {
                return NotFound();
            }

            var donorFlags = await _context.DonorFlags.FindAsync(id);
            if (donorFlags == null)
            {
                return NotFound();
            }
            ViewData["ClientName"] = new SelectList(_context.Client, "ClientId", "ClientName", donorFlags.FlagId);
            return View(donorFlags);
        }

        // POST: DonorFlags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, /*[Bind("FlagId,DateAdded,Comment,DonorId")]*/ DonorFlags donorFlags)
        {
            try
            {
                _context.Update(donorFlags);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Update rejected " + "please check data " + "and try again.");
            }
            return View(donorFlags);
            //if (id != donorFlags.FlagId)
            //{
            //    return NotFound();
            //}

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        _context.Update(donorFlags);
            //        await _context.SaveChangesAsync();
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        if (!DonorFlagsExists(donorFlags.FlagId))
            //        {
            //            return NotFound();
            //        }
            //        else
            //        {
            //            throw;
            //        }
            //    }
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["DonorId"] = new SelectList(_context.Donor, "DonorId", "DonorId", donorFlags.DonorId);
            //return View(donorFlags);
        }

        // GET: DonorFlags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var user = await _manager.GetUserAsync(User);
            var userRoles = await _manager.GetRolesAsync(user);
            if (id == null || _context.DonorFlags == null)
            {
                return NotFound();
            }

            var donorFlags = await _context.DonorFlags
                //.Include(d => d.FlagId)
                .FirstOrDefaultAsync(m => m.FlagId == id);
            if (donorFlags == null)
            {
                return NotFound();
            }

            return View(donorFlags);
        }

        // POST: DonorFlags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DonorFlags == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DonorFlags'  is null.");
            }
            var donorFlags = await _context.DonorFlags.FindAsync(id);
            if (donorFlags != null)
            {

DonorManager2024/Views/DonorFlags/Create.cshtml
@using DonorManager2024.Areas.Identity.Pages.Account
@using Microsoft.AspNetCore.Identity
@using DonorManager2024.ViewModels

@model DonorManager2024.Models.DonorRelated.DonorFlags

@{
    ViewData["Title"] = "Create";
}

<h1>Create a Donor Flag.</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlagName" class="control-label"></label>
                <input asp-for="FlagName" class="form-control" />
                <span asp-validation-for="FlagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Client" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientName"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="checkbox">                
                <input type="checkbox" asp-for="Visibility" value="Visibility" />
                <label asp-for="Visibility" class="checkbox">Visibility</label>
            </div>
            @* <div class="form-group">
                <label asp-for="Donor" class="control-label"></label>
                <select asp-for="DonorId" class ="form-control" asp-items="ViewBag.DonorId"></select>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/DonorFlags/Delete.cshtml
@model DonorManager2024.Models.DonorRelated.DonorFlags

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this Flag?</h3>
<div>
    <h4>DonorFlags</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FlagName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FlagName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Visibility)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Visibility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlagId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DonorManager2024/Views/DonorFlags/Details.cshtml
@model DonorManager2024.Models.DonorRelated.DonorFlags

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DonorFlags</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        @* <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FlagId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FlagId)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FlagName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FlagName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Visibility)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Visibility)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientName)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Donor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Donor.DonorId)
        </dd> *@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FlagId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DonorManager2024/Views/DonorFlags/Edit.cshtml
@model DonorManager2024.Models.DonorRelated.DonorFlags

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DonorFlags</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FlagId" />
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlagName" class="control-label"></label>
                <input asp-for="FlagName" class="form-control" />
                <span asp-validation-for="FlagName" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Visibility" class="control-label"></label>
                <input asp-for="Visibility" class="form-control" />
                <span asp-validation-for="Visibility" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Client" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientName" id="ClientId"></select>
            </div>
            @* <div class="form-group">
                <label asp-for="DonorId" class="control-label"></label>
                <select asp-for="DonorId" class="form-control" asp-items="ViewBag.DonorId"></select>
                <span asp-validation-for="DonorId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/DonorFlags/Index.cshtml
@using DonorManager2024.Models
@using DonorManager2024.Controllers

@model IEnumerable<DonorManager2024.Models.DonorRelated.DonorFlags>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Donor Flags</h1><br />

<p>
    <a asp-action="Create">Create New</a>
</p><br />
<form asp-controller="DonorFlags" asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find Flag by Donor ID:<br/ >
            <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" />
            <a asp-action="Index" class="btn btn-default">Remove Filter</a>
        </p>
    </div>
</form>
<table class="table table-striped border">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlagId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlagName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Visibility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client.ClientName)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.Donor)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FlagId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlagName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Visibility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.ClientName)
            </td>
            @* <td>
                @Html.DisplayFor(modelItem => item.DonorId)
            </td> *@
            <td>
                <a asp-action="Edit" asp-route-id="@item.FlagId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FlagId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FlagId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>