DonorManager2024/Models/Promotions.cs
using System.ComponentModel.DataAnnotations;

namespace DonorManager2024.Models
{
    public class Promotions
    {
        [Key]
        public int PromotionId { get; set; }

        public string PromotionCode { get; set; }

        public string Description { get; set; }

        public string FundType { get; set; }
    }
}

DonorManager2024/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DonorManager2024.Data;
using DonorManager2024.Models;
using Microsoft.AspNetCore.Identity;
using DonorManager.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using FuzzySharp;
using System.Threading.Channels;

namespace DonorManager2024.Controllers
{
    public class PromotionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PromotionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Promotions
        [Authorize(Roles = "Admin, ABData")]
        public async Task<IActionResult> Index(string searchString, string promotionCode, string description, string fundType)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userManager.Users.Include(u => u.ManagedClients).Where(u => u.Id == userId).FirstOrDefault();
            var userRoles = await _userManager.GetRolesAsync(user);
            List<int> allPromotionIds = new List<int>();

            var selectedPromos = userRoles.Contains("Admin") || userRoles.Contains("ABData")
                ? await _context.Promotions.ToListAsync()
                : await _context.Promotions.Where(c => allPromotionIds.Contains(c.PromotionId)).ToListAsync();

            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentFilterPromotionCode"] = promotionCode;
            ViewData["CurrentFilterPromotionDesc"] = description;
            ViewData["CurrentFilterFundType"] = fundType;

            if (string.IsNullOrEmpty(searchString) && string.IsNullOrEmpty(promotionCode)
                && string.IsNullOrEmpty(description) && string.IsNullOrEmpty(fundType))
                return View(selectedPromos.ToList());

            bool success = int.TryParse(searchString, out var promoId);
            if (!success)
                searchString = "";

            if (!string.IsNullOrEmpty(searchString))
                selectedPromos = selectedPromos.Where(c => c.PromotionId == promoId).ToList();

            if (!string.IsNullOrEmpty(promotionCode))
                selectedPromos = selectedPromos.Where(d => Fuzz.Ratio(d.PromotionCode, promotionCode) > 70).ToList();

            if (!string.IsNullOrEmpty(description))
                selectedPromos = selectedPromos.Where(d => Fuzz.Ratio(d.Description, description) > 70).ToList();

            if (!string.IsNullOrEmpty(fundType))
                selectedPromos = selectedPromos.Where(d => Fuzz.Ratio(d.FundType, fundType) > 70).ToList();

            return selectedPromos.Count != 0 ?
                 View(selectedPromos) :
                 NotFound("No Channels Found, Bruh");

            //return _context.Promotions != null ? 
            //              View(await _context.Promotions.ToListAsync()) :
            //              Problem("Entity set 'ApplicationDbContext.Promotions'  is null.");
        }

        // GET: Promotions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Promotions == null)
            {
                return NotFound();
            }

            var promotions = await _context.Promotions
                .FirstOrDefaultAsync(m => m.PromotionId == id);
            if (promotions == null)
            {
                return NotFound();
            }

            return View(promotions);
        }

        // GET: Promotions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Promotions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PromotionId,PromotionCode,Description,FundType")] Promotions promotions)
        {
            if (ModelState.IsValid)
            {
                _context.Add(promotions);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(promotions);
        }

        // GET: Promotions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Promotions == null)
            {
                return NotFound();
            }

            var promotions = await _context.Promotions.FindAsync(id);
            if (promotions == null)
            {
                return NotFound();
            }
            return View(promotions);
        }

        // POST: Promotions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PromotionId,PromotionCode,Description,FundType")] Promotions promotions)
        {
            if (id != promotions.PromotionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promotions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromotionsExists(promotions.PromotionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promotions);
        }

        // GET: Promotions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Promotions == null)
            {
                return NotFound();
            }

            var promotions = await _context.Promotions
                .FirstOrDefaultAsync(m => m.PromotionId == id);
            if (promotions == null)
            {
                return NotFound();
            }

            return View(promotions);
        }

        // POST: Promotions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Promotions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Promotions'  is null.");
            }
            var promotions = await _context.Promotions.FindAsync(id);
            if (promotions != null)
            {
                _context.Promotions.Remove(promotions);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PromotionsExists(int id)
        {
          return (_context.Promotions?.Any(e => e.PromotionId == id)).GetValueOrDefault();
        }
    }
}

DonorManager2024/Views/Promotions/Create.cshtml
@model DonorManager2024.Models.Promotions

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Promotions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PromotionCode" class="control-label"></label>
                <input asp-for="PromotionCode" class="form-control" />
                <span asp-validation-for="PromotionCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FundType" class="control-label"></label>
                <input asp-for="FundType" class="form-control" />
                <span asp-validation-for="FundType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/Promotions/Delete.cshtml
@model DonorManager2024.Models.Promotions

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Promotions</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PromotionCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PromotionCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FundType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FundType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PromotionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DonorManager2024/Views/Promotions/Details.cshtml
@model DonorManager2024.Models.Promotions

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Promotions</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PromotionCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PromotionCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FundType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FundType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PromotionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DonorManager2024/Views/Promotions/Edit.cshtml
@model DonorManager2024.Models.Promotions

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Promotions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PromotionId" />
            <div class="form-group">
                <label asp-for="PromotionCode" class="control-label"></label>
                <input asp-for="PromotionCode" class="form-control" />
                <span asp-validation-for="PromotionCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FundType" class="control-label"></label>
                <input asp-for="FundType" class="form-control" />
                <span asp-validation-for="FundType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/Promotions/Index.cshtml
@model IEnumerable<DonorManager2024.Models.Promotions>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Promotions</h1><br />

<p>
    <a asp-action="Create">Create New</a>
</p><br />
<form asp-controller="Promotions" asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find your Promotion by <br />
            ID: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            Promotion Code: <input type="text" name="promotionCode" value="@ViewData["CurrentFilterPromotionCode"]" />
            Description: <input type="text" name="description" value="@ViewData["CurrentFilterPromotionDesc"]" /><br />
            Fund Type: <input type="text" name="fundType" value="@ViewData["CurrentFilterFundType"]" /><br />
            <input type="submit" value="Search" class="btn btn-default" />
            <a asp-action="Index" class="btn btn-default">Remove Filter</a>
        </p>
    </div>
</form>
<table class="table table-striped border">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PromotionCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FundType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PromotionCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FundType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PromotionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PromotionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PromotionId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>