DonorManager2024/Models/Channels.cs
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;

namespace DonorManager2024.Models
{
    public class Channels
    {
        [Key]
        public int ChannelId { get; set; }

        public string ChannelCode { get; set; }

        public string ChannelDesc { get; set; }

        
    }

    
}

DonorManager2024/Controllers/ChannelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DonorManager2024.Data;
using DonorManager2024.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using DonorManager.Models;
using FuzzySharp;
using Microsoft.AspNetCore.Authorization;

namespace DonorManager2024.Controllers
{
    public class ChannelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ChannelsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Channels
        [Authorize(Roles = "Admin, ABData")]
        public async Task<IActionResult> Index(string searchString, string sortOrder, string channelCode, string channelDesc)
        {            
            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            ViewBag.CodeSort = String.IsNullOrEmpty(sortOrder) ? "code_desc" : "";
                        
            var AllChannels = from ac in _context.Channels.Include(ac => ac.ChannelCode).Include(ac => ac.ChannelDesc) select ac;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userManager.Users.Include(u => u.ManagedClients).Where(u => u.Id == userId).FirstOrDefault();
            var userRoles = await _userManager.GetRolesAsync(user);
            List<int> allChannelIds = new List<int>();          
            
            var selectedChannels = userRoles.Contains("Admin") || userRoles.Contains("ABData")
                ? await _context.Channels.ToListAsync() 
                : await _context.Channels.Where(c => allChannelIds.Contains(c.ChannelId)).ToListAsync();

            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentFilterChannelCode"] = channelCode;
            ViewData["CurrentFilterChannelDesc"] = channelDesc;

            IQueryable<Channels> allChannels = from ac in _context.Channels select ac;

            switch (sortOrder)
            {
                case "code_desc":
                    AllChannels = AllChannels.OrderByDescending(ac=>ac.ChannelCode);
                    break;
                default:
                    AllChannels = AllChannels.OrderBy(ac => ac.ChannelCode);
                    break;
            }

            if (string.IsNullOrEmpty(searchString) && string.IsNullOrEmpty(channelCode)
                && string.IsNullOrEmpty(channelDesc))
                return View(selectedChannels.ToList());

            bool success = int.TryParse(searchString, out var channelId);
            if (!success)
                searchString = "";

            if (!string.IsNullOrEmpty(searchString))
                selectedChannels = selectedChannels.Where(c => c.ChannelId == channelId).ToList();

            if (!string.IsNullOrEmpty(channelCode))
                selectedChannels = selectedChannels.Where(d => Fuzz.Ratio(d.ChannelCode, channelCode) > 50).ToList();

            if (!string.IsNullOrEmpty(channelDesc))
                selectedChannels = selectedChannels.Where(d => Fuzz.Ratio(d.ChannelDesc, channelDesc) > 50).ToList();

            return selectedChannels.Count != 0 ?
                 View(selectedChannels) :
                 NotFound("No Channels Found, Bruh");
             
            /*
            return _context.Channels != null ?
                        View(await _context.Channels.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Channels'  is null.");
            */
        }

        // GET: Channels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Channels == null)
            {
                return NotFound();
            }

            var channels = await _context.Channels
                .FirstOrDefaultAsync(m => m.ChannelId == id);
            if (channels == null)
            {
                return NotFound();
            }

            return View(channels);
        }

        // GET: Channels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Channels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChannelId,ChannelCode,ChannelDesc")] Channels channels)
        {
            if (ModelState.IsValid)
            {
                _context.Add(channels);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(channels);
        }

        // GET: Channels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Channels == null)
            {
                return NotFound();
            }

            var channels = await _context.Channels.FindAsync(id);
            if (channels == null)
            {
                return NotFound();
            }
            return View(channels);
        }

        // POST: Channels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ChannelId,ChannelCode,ChannelDesc")] Channels channels)
        {
            if (id != channels.ChannelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(channels);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChannelsExists(channels.ChannelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(channels);
        }

        // GET: Channels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Channels == null)
            {
                return NotFound();
            }

            var channels = await _context.Channels
                .FirstOrDefaultAsync(m => m.ChannelId == id);
            if (channels == null)
            {
                return NotFound();
            }

            return View(channels);
        }

        // POST: Channels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Channels == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Channels'  is null.");
            }
            var channels = await _context.Channels.FindAsync(id);
            if (channels != null)
            {
                _context.Channels.Remove(channels);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChannelsExists(int id)
        {
          return (_context.Channels?.Any(e => e.ChannelId == id)).GetValueOrDefault();
        }
    }
}

DonorManager2024/Views/Channels/Create.cshtml
@model DonorManager2024.Models.Channels

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Channels</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ChannelCode" class="control-label"></label>
                <input asp-for="ChannelCode" class="form-control" />
                <span asp-validation-for="ChannelCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChannelDesc" class="control-label"></label>
                <input asp-for="ChannelDesc" class="form-control" />
                <span asp-validation-for="ChannelDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/Channels/Delete.cshtml
@model DonorManager2024.Models.Channels

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Channels</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChannelCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChannelCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChannelDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChannelDesc)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ChannelId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DonorManager2024/Views/Channels/Details.cshtml
@model DonorManager2024.Models.Channels

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Channels</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChannelCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChannelCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChannelDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChannelDesc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ChannelId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DonorManager2024/Views/Channels/Edit.cshtml
@model DonorManager2024.Models.Channels

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Channels</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ChannelId" />
            <div class="form-group">
                <label asp-for="ChannelCode" class="control-label"></label>
                <input asp-for="ChannelCode" class="form-control" />
                <span asp-validation-for="ChannelCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChannelDesc" class="control-label"></label>
                <input asp-for="ChannelDesc" class="form-control" />
                <span asp-validation-for="ChannelDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/Channels/Index.cshtml
@model IEnumerable<DonorManager2024.Models.Channels>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Channels List</h1>
<br />

<p>
    <a asp-action="Create">Create New</a><br />
</p>
<form asp-controller="Channels" asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find your Channel by <br />
            ID: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            Channel Code: <input type="text" name="channelCode" value="@ViewData["CurrentFilterChannelCode"]" />
            Channel Desc: <input type="text" name="channelDesc" value="@ViewData["CurrentFilterChannelDesc"]" /><br />
            <input type="submit" value="Search" class="btn btn-default" />
            <a asp-action="Index" class="btn btn-default">Remove Filter</a>
        </p>
    </div>
</form>
<table class="table table-striped border">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.CodeSort">@Html.DisplayNameFor(model => model.ChannelCode)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChannelDesc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChannelCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChannelDesc)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ChannelId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ChannelId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ChannelId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>