DonorManager2024/Models/Client.cs
using DonorManager2024.Models;
using DonorManager2024.Models.DonorRelated;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DonorManager.Models
{
    public class Client
    {
        [Key]
        [DisplayName("ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClientId { get; set; }
        [Required]
        [DisplayName("Code")]
        public string ClientCode { get; set; }
        [MaxLength(100)]
        [DisplayName("Name")]
        public string ClientName { get; set; }
        [MaxLength(100)]
        [DisplayName("Address")]
        public string ClientAddress { get; set; }
        [MaxLength(10)]
        [DisplayName("Phone Number")]
        public string ClientPhone { get; set; }
        [MaxLength(25)]
        [DisplayName("Contact 1")]
        public string Contact1 { get; set; }
        [MaxLength(25)]
        [DisplayName("Contact 2")]
        public string Contact2 { get; set; }
        [MaxLength(25)]
        [DisplayName("Trans Dialog")]
        public string TransDialog { get; set; }

        [DisplayName("Last Updated")]
        public DateTime UpdateDate { get; set; } = DateTime.Now;

        //[ForeignKey(nameof(Client))]
        //public int DonorId { get; set; }        
        //public int CampaignId { get; set; }
        public ICollection<Donor> Donor { get; set; } = new List<Donor>();
        public ICollection<Campaign> Campaigns { get; set; } = new List<Campaign>();
        //public ICollection<DonorFlags> DonorFlags { get; set; } = new List<DonorFlags>();
        //public ICollection<DonorFlagCheckBoxes> DonorFlagCheckBoxes { get; set; } = new List<DonorFlagCheckBoxes>();
    }
}

DonorManager2024/Controllers/DonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DonorManager.Models;
using DonorManager2024.Models;
using DonorManager2024.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using DonorManager2024.Utilities;
using static FuzzySearch.AspNetCore.DamerauLevenshteinDistances.DamerauLevenshteinDistance;
using FuzzySharp;
using DonorManager2024.Models.UsersRelated;
using DonorManager2024.Models.DonorRelated;

namespace DonorManager2024.Controllers
{    
    public class DonorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public DonorController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _manager = userManager;
            _signInManager = signInManager;
        }

        // GET: Donor
        [Authorize(Roles = "Admin, ABData, Client")]
        public async Task<IActionResult> Index(string searchString, string donorName, string donorSurname,
            string donorAddress, string donorFirm, string donorPhone, string donorEmployer, string donorEmail,
            string donorWork, string donorCity, string donorZip, string donorJoin, string donorClient)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _manager.Users.Include(c => c.ManagedClients).Where(u => u.Id == userId).FirstOrDefault();
            var userRoles = await _manager.GetRolesAsync(user);

            List<int> ClientIds = new List<int>();
            foreach (var Client in user.ManagedClients)
            {
                ClientIds.Add(Client.ClientId);
            }

            var selectedDonors =  userRoles.Contains("Admin") || userRoles.Contains("ABData")
                ? await _context.Donor.ToListAsync()
                : await _context.Donor.Include(d => d.Client).Where(d => ClientIds.Contains(d.ClientId)).ToListAsync();

            //var clients = string.IsNullOrEmpty(searchString)
            //    ? await _context.Client.Include(c => c.Donor).ToListAsync()
            //    : await _context.Client.Where(c => c.Donor.Any(d => d.DonorId.ToString().Contains(searchString))).ToListAsync();

            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentFilterName"] = donorName;
            ViewData["CurrentFilterSurname"] = donorSurname;
            ViewData["CurrentFilterAddress"] = donorAddress;
            ViewData["CurrentFilterFirm"] = donorFirm;
            ViewData["CurrentFilterPhone"] = donorPhone;
            ViewData["CurrentFilterEmployer"] = donorEmployer;
            ViewData["CurrentFilterEmail"] = donorEmail;
            ViewData["CurrentFilterWork"] = donorWork;
            ViewData["CurrentFilterCity"] = donorCity;
            ViewData["CurrentFilterZip"] = donorZip;
            ViewData["CurrentFilterJoin"] = donorJoin;
            ViewData["CurrentFilterClient"] = donorClient;

            if (string.IsNullOrEmpty(searchString) && string.IsNullOrEmpty(donorName)
                && string.IsNullOrEmpty(donorSurname) && string.IsNullOrEmpty(donorAddress)
                && string.IsNullOrEmpty(donorFirm) && string.IsNullOrEmpty(donorPhone)
                && string.IsNullOrEmpty(donorEmployer) && string.IsNullOrEmpty(donorEmail)
                && string.IsNullOrEmpty(donorWork) && string.IsNullOrEmpty(donorCity)
                && string.IsNullOrEmpty(donorZip) && string.IsNullOrEmpty(donorJoin)
                && string.IsNullOrEmpty(donorClient))
                return View(selectedDonors);

            bool success = int.TryParse(searchString, out var donorId);
            if (!success)
                searchString = "";

            if (!string.IsNullOrEmpty(searchString))
                selectedDonors = selectedDonors.Where(d => d.DonorId == donorId).ToList();

            if (!string.IsNullOrEmpty(donorName))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.FirstName, donorName) > 50).ToList();

            if (!string.IsNullOrEmpty(donorSurname))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.LastName, donorSurname) > 30).ToList();

            if (!string.IsNullOrEmpty(donorFirm))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.Firm, donorFirm) > 75).ToList();

            if (!string.IsNullOrEmpty(donorAddress))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.PrimaryAddress, donorAddress) > 50).ToList();

            if (!string.IsNullOrEmpty(donorPhone))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.Phone, donorPhone) > 70).ToList();

            if (!string.IsNullOrEmpty(donorEmployer))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.Employer, donorEmployer) > 65).ToList();

            if (!string.IsNullOrEmpty(donorEmail))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.Email, donorEmail) > 45).ToList();

            if (!string.IsNullOrEmpty(donorWork))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.WorkPhone, donorWork) > 30).ToList();

            if (!string.IsNullOrEmpty(donorCity))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.City, donorCity) > 30).ToList();

            if (!string.IsNullOrEmpty(donorZip))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.Zip, donorZip) > 80).ToList();

            if (!string.IsNullOrEmpty(donorJoin))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.JoinDate.ToString(), donorJoin) > 60).ToList();

            if (!string.IsNullOrEmpty(donorClient))
                selectedDonors = selectedDonors.Where(d => Fuzz.Ratio(d.ClientId.ToString(), donorClient) > 60).ToList();

            return selectedDonors.Count != 0 ?
                View(selectedDonors) :
                NotFound("No Donors Found");
        }

        public async Task<IActionResult> Details(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _manager.Users
                .Include(c => c.ManagedClients)
                .FirstOrDefaultAsync(u => u.Id == userId);

            if (user == null)
            {
                return NotFound();
            }

            var userRoles = await _manager.GetRolesAsync(user);

            if (id == null)
            {
                return NotFound();
            }

            IEnumerable<Donor> selectedDonors;

            if (userRoles.Contains("Admin") || userRoles.Contains("ABData"))
            {
                selectedDonors = await _context.Donor.Include(d => d.Client).Where(d => d.DonorId == id).ToListAsync();
            }
            else
            {
                var clientIds = user.ManagedClients.Select(c => c.ClientId).ToList();
                selectedDonors = await _context.Donor.Include(d => d.Client)
                    .Where(d => clientIds.Contains(d.ClientId) && d.DonorId == id)
                    .ToListAsync();
                                
                if (!selectedDonors.Any())
                {
                    selectedDonors = await _context.Donor.Include(d => d.Client)
                        .Where(d => d.ClientId == user.ManagedClients.FirstOrDefault().ClientId && d.DonorId == id)
                        .ToListAsync();
                }
            }

            if (!selectedDonors.Any())
            {
                return NotFound("Donor not found");
            }

            return View(selectedDonors);

        }

        // GET: Donor/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            List<int> ClientIds = new List<int>();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _manager.Users.Include(c => c.ManagedClients).Where(u => u.Id == userId).FirstOrDefault();
            var userRoles = await _manager.GetRolesAsync(user);
            //var donorFlagCheckBoxes = _context.DonorFlagCheckBoxes.ToList();
            bool isAdmin = false;
            if (userRoles.Contains("Admin") || userRoles.Contains("SuperAdmin"))
            {
                isAdmin = true;
            }
            else
            {
                foreach (var Client in user.ManagedClients)
                {
                    ClientIds.Add(Client.ClientId);
                }
            }

            ViewData["ClientName"] = new SelectList(isAdmin ? _context.Client : _context.Client.Where(c => ClientIds.Contains(c.ClientId)), "ClientId", "ClientName");
            
            return View();
        }

        // POST: Donor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, Donor donor)
        {            
            try
            {
                var donorDb = _context.Donor.Include(d => d.Client).Where(d => d.DonorId == id).FirstOrDefault();

                _context.Donor.Add(donor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {

DonorManager2024/Views/Client/Create.cshtml
@using DonorManager2024.Areas.Identity.Pages.Account
@using Microsoft.AspNetCore.Identity
@using DonorManager2024.ViewModels;
@using DonorManager2024.Data

@model CreateClientViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create a Client</h1>

@* <h4>Client</h4> *@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientCode" class="control-label"></label>
                <input asp-for="ClientCode" class="form-control" />
                <span asp-validation-for="ClientCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientAddress" class="control-label"></label>
                <input asp-for="ClientAddress" class="form-control" />
                <span asp-validation-for="ClientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientPhone" class="control-label"></label>
                <input asp-for="ClientPhone" class="form-control" />
                <span asp-validation-for="ClientPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact1" class="control-label"></label>
                <input asp-for="Contact1" class="form-control" />
                <span asp-validation-for="Contact1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact2" class="control-label"></label>
                <input asp-for="Contact2" class="form-control" />
                <span asp-validation-for="Contact2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransDialog" class="control-label"></label>
                <input asp-for="TransDialog" class="form-control" />
                <span asp-validation-for="TransDialog" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SelectedUserId" class="control-label"></label>      
                <select asp-for="@Model.SelectedUserId" class="form-select" asp-items="ViewBag.Users" id="ClientId"></select>
                <input asp-form='@Model.SelectedUserId' type="hidden" />                
            </div>

            <br /><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(function () {
            var $select = $("#ClientId");
            var $options = $select.children("option");

            $options.sort(function (a, b) {
                return $(a).text().toUpperCase().localeCompare($(b).text().toUpperCase());
            });

            $select.empty().append($options);
        });
    </script>
}

DonorManager2024/Views/Client/Delete.cshtml
@model DonorManager.Models.Client

@{
    ViewData["Title"] = "Delete";
}

@* <h1>Delete</h1> *@

<h3>Are you sure you want to delete this client?</h3>
<div>
    @* <h4>Client</h4> *@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransDialog)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransDialog)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DonorManager2024/Views/Client/Details.cshtml
@using DonorManager2024.Models

@model DonorManager.Models.Client
@* 
@model IEnumerable<DonorManager.Models.Client>
 *@
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Client Details</h1>

@* @foreach (var item in Model)
{
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ClientId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.ClientId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ClientCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.ClientCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ClientName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.ClientName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ClientAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.ClientAddress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ClientPhone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.ClientPhone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Contact1)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.Contact1)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Contact2)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.Contact2)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TransDialog)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.TransDialog)
            </dd>

        </dl>
    </div>
    <div>
        <a asp-action="Delete" asp-route-id="@item.ClientId">Delete</a> |
        <a asp-action="Edit" asp-route-id="@item.ClientId">Edit</a> |
        <a asp-action="Index" asp-controller="Donor" asp-route-id="@item.Donor">List of Donors</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}
 *@

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransDialog)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransDialog)
        </dd>

    </dl>
</div>
@if (User.IsInRole("ABData") || User.IsInRole("Admin"))
{
    <div>
        <a asp-action="Create" asp-controller="Transactions">Create Transaction</a> |
        <a asp-action="Delete" asp-route-id="@Model.ClientId">Delete</a> |
        <a asp-action="Edit" asp-route-id="@Model.ClientId">Edit</a> |
        <a asp-action="Index" asp-controller="Donor" asp-route-id="@Model.Donor">List of Donors</a> |
        <a asp-action="Index">Back to List</a> |        
    </div>
}
@if (User.IsInRole("Client"))
{
    <div>
        <a asp-action="Index" asp-controller="Donor" asp-route-id="@Model.Donor">List of Donors</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}

DonorManager2024/Views/Client/Edit.cshtml
@model DonorManager.Models.Client

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Client</h1>

@* <h4>Client</h4> *@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClientId" />
            <div class="form-group">
                <label asp-for="ClientCode" class="control-label"></label>
                <input asp-for="ClientCode" class="form-control" />
                <span asp-validation-for="ClientCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientAddress" class="control-label"></label>
                <input asp-for="ClientAddress" class="form-control" />
                <span asp-validation-for="ClientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientPhone" class="control-label"></label>
                <input asp-for="ClientPhone" class="form-control" />
                <span asp-validation-for="ClientPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact1" class="control-label"></label>
                <input asp-for="Contact1" class="form-control" />
                <span asp-validation-for="Contact1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact2" class="control-label"></label>
                <input asp-for="Contact2" class="form-control" />
                <span asp-validation-for="Contact2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransDialog" class="control-label"></label>
                <input asp-for="TransDialog" class="form-control" />
                <span asp-validation-for="TransDialog" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorManager2024/Views/Client/Index.cshtml
@using DonorManager2024.Models
@using DonorManager2024.Controllers

@model IEnumerable<DonorManager.Models.Client>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Clients</h1>

@if (User.IsInRole("ABData") || User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Donor" asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find your Donor by <br />
            ID: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            First Name: <input type="text" name="donorName" value="@ViewData["CurrentFilterName"]" />
            Last Name: <input type="text" name="donorSurname" value="@ViewData["CurrentFilterSurname"]" />
            Street Address: <input type="text" name="donorAddress" value="@ViewData["CurrentFilterAddress"]" /><br />
            <details>
                <div class="form-actions no-color">
                    Firm: <input type="text" name="donorFirm" value="@ViewData["CurrentFilterFirm"]" />
                    Phone: <input type="text" name="donorPhone" value="@ViewData["CurrentFilterPhone"]" />
                    Employer: <input type="text" name="donorEmployer" value="@ViewData["CurrentFilterEmployer"]" />
                    E-mail: <input type="text" name="donorEmail" value="@ViewData["CurrentFilterEmail"]" /><br />
                    City: <input type="text" name="donorCity" value="@ViewData["CurrentFilterCity"]" />
                    Zip Code: <input type="text" name="donorZip" value="@ViewData["CurrentFilterZip"]" />
                    Work Phone: <input type="text" name="donorWork" value="@ViewData["CurrentFilterWork"]" /><br />
                    Join Date: <input type="text" name="donorJoin" value="@ViewData["CurrentFilterJoin"]" />
                    Client Id: <input type="text" name="donorClient" value="@ViewData["CurrentFilterClient"]" />     
                </div>
            </details>
            <br /><input type="submit" value="Search" class="btn btn-default" />
        </p>
    </div>
</form>

<form asp-controller="Client" asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find a Client: <br />
            Client ID: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            <details>
                <div class="form-actions no-color">
                    Client Name: <input type="text" name="clientName" value="@ViewData["CurrentFilerClientName"]" />
                    Client Code: <input type="text" name="clientCode" value="@ViewData["CurrentFilterClientCode"]" />
                    Client Address: <input type="text" name="clientAddress" value="@ViewData["CurrentFilerClientAddress"]" />
                    Client Phone: <input type="text" name="clientPhone" value="@ViewData["CurrentFilterClientPhone"]" /><br />
                    Contact 1: <input type="text" name="clientContact1" value="@ViewData["CurrentFilerContact1"]" />
                    Contact 2: <input type="text" name="clientContact2" value="@ViewData["CurrentFilterContact2"]" />
                    Trans Dialog: <input type="text" name="clientDialog" value="@ViewData["CurrentFilterTransDialog"]" />
                </div>
            </details>          
            <input type="submit" value="Search" class="btn btn-default" />
        </p>
    </div>
</form>

<table class="table table-striped border">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.ClientId">
                @Html.DisplayFor(modelItem => item.ClientName)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdateDate)
            </td>
                @if (User.IsInRole("ABData") || User.IsInRole("Admin"))
                {
                    <td>                        
                        <a asp-action="Edit" asp-route-id="@item.ClientId">Edit</a> |
                        <a asp-controller="Campaigns" asp-action="Index" asp-route-id="@item.Campaigns">Campaigns</a> |
                        <a asp-controller="Donor" asp-action="Index" asp-route-id="@item.Donor">Donors</a> |
                        <a asp-action="Details" asp-route-id="@item.ClientId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ClientId">Delete</a>
                    </td>
                }
                @if (User.IsInRole("Client"))
                {
                    <td>
                        <a asp-controller="Campaigns" asp-action="Index" asp-route-id="@item.Campaigns">Campaigns</a> |
                        <a asp-controller="Donor" asp-action="Index" asp-route-id="@item.Donor">Donors</a> |
                        <a asp-action="Details" asp-route-id="@item.ClientId">Details</a> |
                    </td>
                }
        </tr>
}
    </tbody>
</table>

@* @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(function () {
            var $select = $("#ClientId");
            var $options = $select.children("option");

            $options.sort(function (a, b) {
                return $(a).text().toUpperCase().localeCompare($(b).text().toUpperCase());
            });

            $select.empty().append($options);
        });
    </script>
} *@